download_crate_static () 
{ 
    package=$1;
    version=$2;
    curl -L https://static.crates.io/crates/${package}/${package}-${version}.crate -o ~/balena-jetson-jp5/build/downloads/${package}-${version}.crate
}


download_crate_static anyhow 1.0.62
download_crate_static bitflags 1.2.1
download_crate_static cc 1.0.46
download_crate_static clap 3.2.17
download_crate_static cfg-if 0.1.10
download_crate_static clap_derive 3.2.17
download_crate_static cstr-argument 0.0.2
download_crate_static glob 0.3.0
download_crate_static errno-dragonfly 0.1.1
download_crate_static heck 0.4.0
download_crate_static errno 0.2.4
download_crate_static indexmap 1.9.1
download_crate_static exec 0.3.1
download_crate_static md-5 0.10.1
download_crate_static gcc 0.3.55
download_crate_static os_str_bytes 6.3.0
download_crate_static getopts 0.2.21
download_crate_static path-absolutize 3.0.13
download_crate_static path-dedot 3.0.17
download_crate_static libc 0.2.65
download_crate_static libsystemd-sys 0.2.2
download_crate_static regex-syntax 0.6.27
download_crate_static regex 1.6.0
download_crate_static log 0.4.8
download_crate_static memchr 1.0.2
download_crate_static textwrap 0.15.0
download_crate_static nix 0.15.0
download_crate_static pkg-config 0.3.16
download_crate_static systemd 0.4.0
download_crate_static unicode-width 0.1.6
download_crate_static utf8-cstr 0.1.6
download_crate_static void 1.0.2
download_crate_static winapi 0.3.8
download_crate_static actix-net 0.2.6
download_crate_static errno 0.2.3
download_crate_static actix-web 0.7.19
download_crate_static kernel32-sys 0.2.2
download_crate_static aead 0.3.2
download_crate_static aes-gcm 0.8.0
download_crate_static actix 0.7.9
download_crate_static libc 0.2.36
download_crate_static actix_derive 0.3.2
download_crate_static winapi-build 0.1.1
download_crate_static addr2line 0.15.2
download_crate_static winapi 0.2.8
download_crate_static adler32 1.2.0
download_crate_static aes 0.6.0
download_crate_static aes-gcm 0.8.0
download_crate_static aes-soft 0.6.4
download_crate_static aesni 0.10.0
download_crate_static aho-corasick 0.7.15
download_crate_static anyhow 1.0.2
download_crate_static assert_cli 0.6.3
download_crate_static autocfg 0.1.8
download_crate_static backtrace 0.3.59
download_crate_static base64 0.10.1
download_crate_static block-buffer 0.7.3
download_crate_static block-padding 0.1.5
download_crate_static brotli-sys 0.3.2
download_crate_static brotli2 0.3.2
download_crate_static byte-tools 0.3.1
download_crate_static byteorder 1.3.4
download_crate_static bytes 0.4.12
download_crate_static cc 1.0.73
download_crate_static cipher 0.2.5
download_crate_static colored 1.9.3
download_crate_static cookie 0.11.4
download_crate_static cookie 0.12.0
download_crate_static cookie_store 0.7.0
download_crate_static core-foundation-sys 0.7.0
download_crate_static core-foundation 0.7.0
download_crate_static cpufeatures 0.2.2
download_crate_static cpuid-bool 0.2.0
download_crate_static crossbeam-deque 0.7.4
download_crate_static crossbeam-epoch 0.8.2
download_crate_static crossbeam-queue 0.2.3
download_crate_static crossbeam-utils 0.7.2
download_crate_static crypto-mac 0.10.1
download_crate_static ctr 0.6.0
download_crate_static dbus 0.6.5
download_crate_static digest 0.8.1
download_crate_static either 1.7.0
download_crate_static encoding_rs 0.8.31
download_crate_static environment 0.1.1
download_crate_static error-chain 0.12.4
download_crate_static error-chain 0.8.1
download_crate_static failure 0.1.8
download_crate_static failure_derive 0.1.8
download_crate_static flate2 1.0.8
download_crate_static form_urlencoded 1.0.1
download_crate_static fuchsia-zircon-sys 0.3.3
download_crate_static fuchsia-zircon 0.3.3
download_crate_static futures-cpupool 0.1.8
download_crate_static futures 0.1.31
download_crate_static generic-array 0.12.4
download_crate_static ghash 0.3.1
download_crate_static gimli 0.24.0
download_crate_static h2 0.1.26
download_crate_static hex 0.3.2
download_crate_static hkdf 0.10.0
download_crate_static hmac 0.10.1
download_crate_static http-body 0.1.0
download_crate_static http 0.1.21
download_crate_static httparse 1.7.1
download_crate_static humantime 1.3.0
download_crate_static hyper-tls 0.3.2
download_crate_static hyper 0.12.36
download_crate_static idna 0.1.5
download_crate_static idna 0.2.1
download_crate_static ipconfig 0.1.9
download_crate_static itoa 1.0.3
download_crate_static language-tags 0.2.2
download_crate_static libc 0.2.127
download_crate_static libdbus-sys 0.2.2
download_crate_static lock_api 0.3.4
download_crate_static lru-cache 0.1.2
download_crate_static maplit 1.0.2
download_crate_static matches 0.1.9
download_crate_static maybe-uninit 2.0.0
download_crate_static md-5 0.8.0
download_crate_static memchr 2.3.0
download_crate_static memoffset 0.5.6
download_crate_static mime 0.3.16
download_crate_static miniz-sys 0.1.12
download_crate_static miniz_oxide 0.2.3
download_crate_static miniz_oxide 0.4.4
download_crate_static miniz_oxide_c_api 0.2.0
download_crate_static mio-uds 0.6.8
download_crate_static mio 0.6.23
download_crate_static miow 0.2.2
download_crate_static native-tls 0.2.4
download_crate_static net2 0.2.37
download_crate_static nom 4.2.3
download_crate_static object 0.24.0
download_crate_static once_cell 1.13.0
download_crate_static opaque-debug 0.2.3
download_crate_static openssl-macros 0.1.0
download_crate_static openssl-sys 0.9.75
download_crate_static openssl 0.10.41
download_crate_static owning_ref 0.4.1
download_crate_static parking_lot 0.9.0
download_crate_static parking_lot_core 0.6.2
download_crate_static path-absolutize 2.0.2
download_crate_static path-dedot 2.0.5
download_crate_static percent-encoding 1.0.1
download_crate_static percent-encoding 2.1.0
download_crate_static pkg-config 0.3.25
download_crate_static polyval 0.4.5
download_crate_static publicsuffix 1.5.4
download_crate_static rand 0.4.6
download_crate_static rand 0.5.6
download_crate_static rand_core 0.4.2
download_crate_static redox_syscall 0.1.57
download_crate_static regex 1.4.6
download_crate_static reqwest 0.9.24
download_crate_static resolv-conf 0.6.3
download_crate_static rustc-demangle 0.1.21
download_crate_static ryu 1.0.11
download_crate_static schannel 0.1.20
download_crate_static security-framework-sys 0.4.3
download_crate_static security-framework 0.4.4
download_crate_static serde 1.0.100
download_crate_static serde_derive 1.0.94
download_crate_static serde_json 1.0.83
download_crate_static serde_urlencoded 0.5.5
download_crate_static smallvec 0.6.14
download_crate_static socket2 0.3.19
download_crate_static string 0.2.1
download_crate_static syn 0.15.44
download_crate_static tempdir 0.3.7
download_crate_static tempfile 3.0.5
download_crate_static tokio-buf 0.1.1
download_crate_static tokio-codec 0.1.2
download_crate_static tokio-current-thread 0.1.7
download_crate_static tokio-executor 0.1.10
download_crate_static tokio-fs 0.1.7
download_crate_static tokio-io 0.1.13
download_crate_static tokio-openssl 0.2.1
download_crate_static tokio-reactor 0.1.12
download_crate_static tokio-signal 0.2.9
download_crate_static tokio-sync 0.1.8
download_crate_static tokio-tcp 0.1.4
download_crate_static tokio-threadpool 0.1.18
download_crate_static tokio-timer 0.2.13
download_crate_static tokio-udp 0.1.6
download_crate_static tokio-uds 0.2.7
download_crate_static tokio 0.1.22
download_crate_static tower-service 0.1.0
download_crate_static trust-dns-proto 0.5.0
download_crate_static trust-dns-proto 0.6.3
download_crate_static trust-dns-resolver 0.10.3
download_crate_static try-lock 0.2.3
download_crate_static try_from 0.3.2
download_crate_static unicode-bidi 0.3.8
download_crate_static unicode-normalization 0.1.9
download_crate_static unicode-xid 0.2.3
download_crate_static universal-hash 0.4.1
download_crate_static url 1.7.2
download_crate_static url 2.2.2
download_crate_static uuid 0.7.4
download_crate_static v_escape 0.7.4
download_crate_static v_escape_derive 0.5.6
download_crate_static v_htmlescape 0.4.5
download_crate_static version_check 0.1.5
download_crate_static want 0.2.0
download_crate_static widestring 0.2.2
download_crate_static windows-sys 0.36.1
download_crate_static windows_aarch64_msvc 0.36.1
download_crate_static windows_i686_gnu 0.36.1
download_crate_static windows_i686_msvc 0.36.1
download_crate_static windows_x86_64_gnu 0.36.1
download_crate_static windows_x86_64_msvc 0.36.1
download_crate_static winreg 0.5.1
download_crate_static winreg 0.6.2
download_crate_static ws2_32-sys 0.2.1
